[package]
name = "launchpad-common"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@numbat.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "0.54.2"

[dependencies.dharitri-sc-modules]
version = "0.54.2"
